---
run:
  build-tags:
    - apparmor
    - seccomp
    - selinux
  # Don't exceed number of threads available when running under CI
  concurrency: 4
linters:
  enable-all: true
  disable:
    # All these break for one reason or another
    - deadcode
    - depguard
    - dupl
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - golint
    - gosec
    - gosimple
    - lll
    - maligned
    - prealloc
    - scopelint
    - structcheck
    - typecheck
    - unconvert
    - varcheck
