FROM scratch
  <<<<<<< release-1.17
ADD --chown=1:1 https://raw.githubusercontent.com/containers/buildah/master/LICENSE /
  =======
ADD --chown=1:1 https://raw.githubusercontent.com/containers/buildah/main/LICENSE /
  >>>>>>> release-1.22
